app/booking/models.py
import datetime as dt
import random, string
from sqlalchemy import event

from app import db

class Client(db.Model):
	id = db.Column(db.Integer, primary_key=True)
	first_name = db.Column(db.String)
	last_name = db.Column(db.String)
	phone = db.Column(db.String)
	email = db.Column(db.String)
	created = db.Column(db.DateTime, default=dt.datetime.utcnow())

	def __str__(self):
		return self.email

	def find_bookings(self):
		return RequestBooking.query.filter_by(requestor=self).all()

class RequestBooking(db.Model):
	__tablename__ = 'request'
	id = db.Column(db.Integer, primary_key=True)
	dtStart = db.Column(db.DateTime)
	dtEnd = db.Column(db.DateTime)
	dtRequest = db.Column(db.DateTime, default=dt.datetime.utcnow())
	status = db.Column(db.String)
	dtStatus = db.Column(db.DateTime)
	requestor_id = db.Column(db.Integer, db.ForeignKey('client.id'))
	requestor = db.relationship('Client',backref=db.backref('requests', lazy='dynamic'))
	note = db.Column(db.Text)
	receipt = db.Column(db.String(8))

	def allocate_receipt(self):
		s=string.lowercase+string.digits
		uid=''.join(random.sample(s,8))
		if RequestBooking.query.filter_by(receipt=uid).first() is None:
			self.receipt = uid
			return True

app/booking/forms.py
from flask_wtf import Form
from wtforms import validators, StringField, DateTimeField
from wtforms.widgets import TextArea
from wtforms.fields.html5 import EmailField
from wtforms.validators import ValidationError
import re

# from user.models import User
    
class BookingForm(Form):
    first_name = StringField('First Name', [validators.DataRequired()])
    last_name = StringField('Last Name', [validators.DataRequired()])
    email = EmailField('Email Address', [
        validators.DataRequired(), 
        validators.Email()
        ]    
    )
    phone = StringField('Telephone Number', [validators.DataRequired()])
    dateStart = DateTimeField('Request Hall From', format='%d/%m/%Y %I:%M %p')
    dateEnd = DateTimeField('Request Hall Until', format='%d/%m/%Y %I:%M %p')

app/booking/__init__.py
import functools, os, re, string, random, datetime
from flask import Blueprint, render_template, flash, redirect, session, url_for, request, g, Markup, abort
from datetime import datetime
from flask_security import login_required, current_user, roles_required

from forms import BookingForm
from app import db
from models import Client, RequestBooking

booking_app = Blueprint('booking_app', __name__, template_folder='booking')

@booking_app.route('/')
@booking_app.route('/home')
def home():
	return render_template('booking/index.html')

@booking_app.route('/form', methods=['GET','POST'])
def form():
	form = BookingForm()
	if form.validate_on_submit():
		cl = Client.query.filter_by(email=form.email.data).first()
		if not cl:
			cl = Client(
				first_name = form.first_name.data,
				last_name = form.last_name.data,
				email = form.email.data,
				phone = form.phone.data)
			db.session.add(cl)
		rq = RequestBooking(
			dtStart = form.dateStart.data,
			dtEnd = form.dateEnd.data,
			status = 'new',
			dtStatus = datetime.utcnow(),
			requestor = cl)
		rq.allocate_receipt()
		db.session.add(rq)
		db.session.commit()
		# flash('Thank you, your booking request has been sent', 'success')
		return redirect(url_for('booking_app.track', booking_ref=rq.receipt))
	return render_template('booking/form.html',form=form)

@booking_app.route('/track/<booking_ref>')
def track(booking_ref):
	b = RequestBooking.query.filter_by(receipt=booking_ref).first_or_404()
	if b:
		cl = b.requestor
		return render_template('booking/confirmation.html', booking=b, client=cl)
	else:
		return "<h1>That booking doesn't exist</h1>"

@booking_app.route('/admin/')
@login_required
@roles_required('admin','-bookings')
def admin():
	new_bookings = RequestBooking.query.filter_by(status='new').all()
	confirmed_bookings = RequestBooking.query.filter_by(status='confirmed').all()
	return render_template('booking/admin.html', new_bookings=new_bookings, confirmed_bookings=confirmed_bookings)

@booking_app.route('/approve/<booking_id>')
@login_required
@roles_required('admin','-bookings')
def approve(booking_id):
	booking = RequestBooking.query.get(booking_id)
	if booking:
		booking.status = "confirmed"
		db.session.commit()
		msg = 'Booking %s confirmed' % (booking.receipt)
		flash(msg, 'success')
		return redirect(url_for('booking_app.admin'))

@booking_app.route('/cancel/<booking_id>')
@login_required
@roles_required('admin','-bookings')
def cancel(booking_id):
	booking = RequestBooking.query.get(booking_id)
	if booking:
		booking.status = "cancelled"
		db.session.commit()
		msg = 'Booking %s cancelled' % (booking.receipt)
		flash(msg, 'danger')
		return redirect(url_for('booking_app.admin'))

@booking_app.route('/admin/client/<client_id>')
@login_required
@roles_required('admin','-bookings')
def admin_client(client_id):
	client = Client.query.get(client_id)
	if client:
		bookings = client.find_bookings()
		return render_template('booking/client.html', client=client, bookings=bookings)
	else:
		return redirect(url_for('admin'))

@booking_app.route('/admin/booking/<booking_id>')
@login_required
@roles_required('admin','-bookings')
def admin_booking(booking_id):
	booking = RequestBooking.query.get(booking_id)
	if booking:
		return render_template('booking/booking-detail.html', booking=booking)
	else:
		return redirect(url_for('admin'))

app/templates/booking/admin.html
{% extends "base.html" %}

{% block title %}Hall Booking - {% endblock %}

{% block content %}

  <div class="container contentalign brandtext brandtext-inverse">

  {% for category, message in get_flashed_messages(with_categories=true) %}
  <div class="alert alert-{{ category }} alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <p>{{ message }}</p>
  </div>
  {% endfor %}
  
    <div class="panel panel-warning">

      <div class="panel-heading">New Booking Requests</div>
      <div class="panel-body">
        <!-- New booking requests -->

        {% if not new_bookings %}
        
          <div class="brandtext brandtext-inverse well">
          <i>No new bookings</i>
          </div>

        {% else %}
          
          <table class="table table-striped">
          
            <th>Reference</th>
            <th>Client Name</th>
            <th>Request Date</th>
            <th>Date/time from</th>
            <th>Date/time to</th>
            <th></th>

            {% for booking in new_bookings %}
            
              <tr>
                <td><a href="{{ url_for('booking_app.admin_booking', booking_id=booking.id) }}">{{ booking.receipt }}</a></td>
                <td><a href="{{ url_for('booking_app.admin_client', client_id=booking.requestor.id) }}">{{ booking.requestor.first_name ~ " " ~ booking.requestor.last_name }}</a></td>
                <td>{{ booking.dtRequest.strftime('%d/%m/%y') }}</td>
                <td>{{ booking.dtStart.strftime('%d/%m/%y') }}</td>
                <td>{{ booking.dtEnd.strftime('%d/%m/%y') }}</td>
                <td>
                  <div class="btn-group">
                    <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Action <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                      <li><a href="{{ url_for('booking_app.approve', booking_id=booking.id) }}">Confirm/Approve</a></li>
                      <li><a href="{{ url_for('booking_app.cancel', booking_id=booking.id) }}">Cancel</a></li>
                    </ul>
                  </div>
                </td>
              </tr>
            
            {% endfor %}
            
          </table>

        {% endif %}

      </div>

    </div>

    <div class="panel panel-primary">
      
      <div class="panel-heading">Confirmed Booking Requests</div>
      <div class="panel-body">

        {% if not confirmed_bookings %}
          <div class="brandtext brandtext-inverse well">
          <i>No confirmed bookings</i>
          </div>

        {% else %}

          <table class="table table-striped">
        
            <th>Reference</th>
            <th>Client Name</th>
            <th>Request Date</th>
            <th>Date/time from</th>
            <th>Date/time to</th>
            <th></th>
            
            {% for booking in confirmed_bookings %}
            
              <tr>
                <td><a href="{{ url_for('booking_app.track', booking_ref=booking.receipt) }}">{{ booking.receipt }}</a></td>
                <td><a href="{{ url_for('booking_app.admin_client', client_id=booking.requestor.id) }}">{{ booking.requestor.first_name ~ " " ~ booking.requestor.last_name }}</a></td>
                <td>{{ booking.dtRequest.strftime('%d/%m/%y') }}</td>
                <td>{{ booking.dtStart.strftime('%d/%m/%y') }}</td>
                <td>{{ booking.dtEnd.strftime('%d/%m/%y') }}</td>
                <td>
                  <div class="btn-group">
                    <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Action <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                      <li><a href="{{ url_for('booking_app.cancel', booking_id=booking.id) }}">Cancel</a></li>
                    </ul>
                  </div>
                </td>
              </tr>
            
            {% endfor %}
            
          </table>

        {% endif %}

    </div>

  </div>

</div>

{% endblock %}

{% block extra_scripts %}



{% endblock %}

app/templates/booking/booking-detail.html
{% extends "base.html" %}

{% block title %}Hall Booking - {% endblock %}

{% block content %}

  <div class="container contentalign brandtext brandtext-inverse">

  {% for category, message in get_flashed_messages(with_categories=true) %}
  <div class="alert alert-{{ category }} alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <p>{{ message }}</p>
  </div>
  {% endfor %}

    <div class="row">
    <div class="col-md-2">
      <a href="/booking/admin" class="btn btn-default"><span class="glyphicon glyphicon-chevron-left"></span> Back</a>
    </div>
    </div>
    
    <br />

    <div class="panel panel-primary">

      <div class="panel-heading">Client Details</div>
      <div class="panel-body">

        <table class="table table-striped">

          <tr><td>Client Name</td><td>{{ booking.requestor.first_name ~ " " ~ booking.requestor.last_name }}</td></tr>
          <tr><td>Telephone</td><td>{{ booking.requestor.phone }}</td></tr>
          <tr><td>Email</td><td><a href="mailto:{{ booking.requestor.email }}">{{ booking.requestor.email }}</a></td></tr>

        </table>

      </div>
    </div>

    <div class="panel panel-primary">

      <div class="panel-heading">Booking Details</div>
      <div class="panel-body">

        <table class="table table-striped">

          <tr><td>Date of Request</td><td>{{ booking.dtRequest.strftime('%d/%m/%y %H:%M') }}</td></tr>
          <tr><td>Start Date & Time</td><td>{{ booking.dtStart.strftime('%d/%m/%y %H:%M') }}</td></tr>
          <tr><td>End Date & Time</td><td>{{ booking.dtEnd.strftime('%d/%m/%y %H:%M') }}</a></td></tr>
          <tr><td>Status</td><td>{{ booking.status }}</td></tr>
          <tr><td>Date of Last Status Change</td><td>{{ booking.dtStatus.strftime('%d/%m/%y %H:%M') }}</td></tr>
          <tr><td>Note</td><td>{{ booking.note }}</td></tr>

        </table>

      </div>

    </div>

</div>

{% endblock %}

{% block extra_scripts %}



{% endblock %}

app/templates/booking/calendar.html
{% extends "base.html" %}

{% block title %}Hall Booking - {% endblock %}

{% block content %}

<div class="container contentalign">

	{% for category, message in get_flashed_messages(with_categories=true) %}
	<div class="alert alert-{{ category }} alert-dismissable">
	  	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	    <p>{{ message }}</p>
	</div>
	{% endfor %}

	<h2 id="page-header">Hall Booking{% block content_title %}{% endblock %}</h2>
	<h3>Availability Calendar</h3>

	<hr>

	<div class="row">


		
	</div>

	<div class="row">

		<div class="col-md-10">

			<a href="/" class="btn btn-default"><span class="glyph glyph-tick"></span>Cancel</a>

		</div>
		
		<div class="col-md-2"></div>

			<a href="/booking/booking_rules" class="btn btn-primary"><span class="glyph glyph-tick"></span>Select Date</a>

		</div>

	</div>

</div>

{% endblock %}

{% block extra_scripts %}


{% endblock %}

app/templates/booking/client.html
{% extends "base.html" %}

{% block title %}Hall Booking - {% endblock %}

{% block content %}

  <div class="container contentalign brandtext brandtext-inverse">

  {% for category, message in get_flashed_messages(with_categories=true) %}
  <div class="alert alert-{{ category }} alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <p>{{ message }}</p>
  </div>
  {% endfor %}

    <div class="row">
    <div class="col-md-2">
      <a href="/booking/admin" class="btn btn-default"><span class="glyphicon glyphicon-chevron-left"></span> Back</a>
    </div>
    </div>
    
    <br />

    <div class="panel panel-primary">

      <div class="panel-heading">Client Details</div>
      <div class="panel-body">

        <table class="table table-striped">

          <tr><td>First Name</td><td>{{ client.first_name }}</td></tr>
          <tr><td>Surname</td><td>{{ client.last_name }}</td></tr>
          <tr><td>Telephone</td><td>{{ client.phone }}</td></tr>
          <tr><td>Email</td><td><a href="mailto:{{ client.email }}">{{ client.email }}</a></td></tr>

        </table>

      </div>
    </div>

    <div class="panel panel-primary">

      <div class="panel-heading">Client Bookings</div>
      <div class="panel-body">

        <table class="table table-striped">

          <th>Reference</th>
          <th>Request Date</th>
          <th>Date/time from</th>
          <th>Date/time to</th>
          <th>Status</th>
          <th></th>

          {% for booking in bookings %}
          
            <tr>
              <td><a href="{{ url_for('booking_app.track', booking_ref=booking.receipt) }}">{{ booking.receipt }}</a></td>
              <td>{{ booking.dtRequest.strftime('%d/%m/%y %H:%M') }}</td>
              <td>{{ booking.dtStart.strftime('%d/%m/%y %H:%M') }}</td>
              <td>{{ booking.dtEnd.strftime('%d/%m/%y %H:%M') }}</td>
              <td>{{ booking.status }}</td>
              <td>
                <div class="btn-group">
                  <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Action <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu">
                    {% if not booking.status=='confirmed' %}<li><a href="{{ url_for('booking_app.approve', booking_id=booking.id) }}">Confirm/Approve</a></li>{% endif %}
                    {% if not booking.status=='cancelled' %}<li><a href="{{ url_for('booking_app.cancel', booking_id=booking.id) }}">Cancel</a></li>{% endif %}
                  </ul>
                </div>
              </td>
            </tr>
          
          {% endfor %}

        </table>

      </div>

    </div>

</div>

{% endblock %}

{% block extra_scripts %}



{% endblock %}

app/templates/booking/confirmation.html
{% extends "base.html" %}

{% block title %}Hall Booking - {% endblock %}

{% block content %}

  <div class="container contentalign brandtext brandtext-inverse">

	{% if booking.status == "new" %}

	  	<div class="panel panel-success">

	  		<div class="panel-heading">
	  			
		  		<h4><span class="glyphicon glyphicon-time">&nbsp;</span> Thank you - your booking request has been received.</h4>

	  		</div>
	  		<div class="panel-body">

	  			<h4>We're checking availability at the hall and will get back to you ASAP.  <b>Your booking is not yet confirmed.</b></h4><br />

	  			<p>
	  			<b>Your reference is <u>{{ booking.receipt }}</u></b>. To track on your booking status, bookmark this page.
	  			</p><br />

	  			<p>For booking amendments / cancellations, email <a href="mailto:bookings@gumleyvillagehall.org.uk">bookings@gumleyvillagehall.org.uk</a></p>

	  		</div>

	  	</div>

	 {% elif booking.status == "confirmed" %}

	 	<div class="panel panel-primary">

	  		<div class="panel-heading">
	  			
		  		<h4><span class="glyphicon glyphicon-ok">&nbsp;</span>Your booking is confirmed - booking reference {{ booking.receipt }}</h4>

	  		</div>
	  		<div class="panel-body">

	  			<p>Your booking is confirmed with the details below.</p>

	  			<br />

	  			<table class="table">

	  				<tr><td>Start Date & Time:</td><td>{{ booking.dtStart.strftime('%d %b %Y %-I:%M %p') }}</td></tr>
	  				<tr><td>End Date & Time:</td><td>{{ booking.dtEnd.strftime('%d %b %Y %-I:%M %p') }}</td></tr>
	  				<tr><td>Booking Name:</td><td>{{ booking.requestor.first_name ~ " " ~ booking.requestor.last_name }}</td></tr>
	  				<tr><td>Contact Details:</td><td>Phone: {{ booking.requestor.phone }}</td><td>Email: {{ booking.requestor.email }}</td></tr>

	  			</table>

	  		</div>

	  	</div>

	{% endif %}

  </div>

{% endblock %}

{% block extra_scripts %}



{% endblock %}

app/templates/booking/form.html
{% extends "base.html" %}

{% block title %}Hall Booking - {% endblock %}

{% block content %}

<div class="container contentalign brandtext brandtext-inverse">

  <h2 id="page-header">Booking Request</h2><hr>

  <p>To book the hall, complete and submit the request form below - we'll get back to you with confirmation</p><br />

	{% for category, message in get_flashed_messages(with_categories=true) %}
	<div class="alert alert-{{ category }} alert-dismissable">
	  	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	    <p>{{ message }}</p>
	</div>
	{% endfor %}

  {% from "_formhelpers.html" import render_field %}

  <div class="row">

    <div class="col-md-6 col-md-offset-3">

    	<form method="POST" action="" role="form" class="form-horizontal">

          {{ form.hidden_tag() }}

          {{ render_field(form.first_name, class='form-control') }}
          {{ render_field(form.last_name, class='form-control') }}
          {{ render_field(form.email, class='form-control') }}
          {{ render_field(form.phone, class='form-control') }}

          {{ render_field(form.dateStart, class='form-control requestDate', type='datetime', id='startDate') }}
          {{ render_field(form.dateEnd, class='form-control requestDate', type='datetime', id='endDate') }}

          <a href="/" class="btn btn-default pull-left"><span class="glyph glyph-tick"></span>Cancel</a>
          <button type="submit" class="btn btn-default pull-right btn-primary">Submit</button>

        </div>

      </form>

    </div>

  </div>

{% endblock %}

{% block extra_scripts %}

  <!-- <script type="text/javascript" src="../../static/js/bundle.js"></script> -->
  <script type="text/javascript" src="../static/js/moment.js"></script>
  <script type="text/javascript" src="../static/js/daterangepicker.js"></script>
  <script type="text/javascript">
    
    $(function() {
        $('.requestDate').daterangepicker({
          singleDatePicker: true,
          timePicker: true,
          timePickerIncrement: 30,
          timePicker24Hour: true,
          autoApply: true,
          locale: {
            format: 'DD/MM/YYYY h:mm A'
          },
          showDropdowns: true,
        });
    });

  </script>

{% endblock %}

app/templates/booking/index.html
{% extends "base.html" %}

{% block title %}Hall Booking - {% endblock %}

{% block header %}

	<style type="text/css">
		
	.incr-margin {
		margin-left: 5px !important;
		margin-right: 5px !important;
	}

	</style>

{% endblock %}

{% block content %}

<div class="container contentalign brandtext">

	{% for category, message in get_flashed_messages(with_categories=true) %}
	<div class="alert alert-{{ category }} alert-dismissable">
	  	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	    <p>{{ message }}</p>
	</div>
	{% endfor %}

	<h2 id="page-header">Hall Booking{% block content_title %}{% endblock %}</h2>

	<hr>

	<p>Hold your next event at Gumley Village Hall</p>

	<p>
		Gumley Village Hall sits at the centre of Gumley village and provides a versatile space which can be used for meetings, parties, events, classes.   With beautiful views across south Leicestershire from the rear of the hall, and nestled at the heart of our small village community, it's a friendly and welcoming space for hire.
	</p>
	<p>
		We've had BBQs in the space outside with hungry folk inside and out, children's parties, anniversary dinners and pop up pub nights, quiz nights, WI and ramblers meets, Pilates and yoga, charity events and pop up cafes.  
	</p>
	<p>
		The hall can hired for 2+ hours and provides some parking directly outside or along the quiet village itself.    
	</p>

	<p>Features:</p>

	<ul>
		<li>Capacity for up to x</li>
		<li>Limited parking</li>
		<li>etc.</li>
	</ul>

	<h3>Terms, Conditions & Rates</h3>

	<div class="row">

		<div class="col-md-6">

			<div class="panel panel-default">

				<div class="panel-heading">Current Rates</div>

<!-- 				<div class="panel-body">[current rates displayed here]</div> 
 -->
				<table class="table">
					<tr>
						<td>Per Hour</td>
						<td>£x.xx</td>
					</tr>
				</table>

			</div>

		</div>

		<div class="col-md-6">

			<div class="panel panel-default">

				<div class="panel-heading">Terms & Conditions</div>

				<div class="panel-body">[T&Cs]</div> 

			</div>

		</div>

	</div>
		
	<div class="row">

		<div class="col-md-12">

			<a href="/" class="btn btn-default pull-left"><span class="glyph glyph-tick"></span>Cancel</a>

			
			<a href="{{ url_for('booking_app.form') }}" class="btn btn-primary pull-right"><span class="glyph glyph-tick"></span>Accept & Proceed</a>

		</div>

	</div>

</div>

{% endblock %}

{% block extra_scripts %}

	

{% endblock %}