app/booking/__init__.py
import functools, os, re, string, random, datetime
from flask import Blueprint, render_template, flash, redirect, session, url_for, request, g, Markup, abort
from datetime import datetime
from flask_security import login_required, current_user, roles_required

from forms import BookingForm
from app import db
from models import Client, RequestBooking

booking_app = Blueprint('booking_app', __name__, template_folder='booking')

@booking_app.route('/')
@booking_app.route('/home')
def home():
	return render_template('booking/index.html')

@booking_app.route('/form', methods=['GET','POST'])
def form():
	form = BookingForm()
	if form.validate_on_submit():
		cl = Client.query.filter_by(email=form.email.data).first()
		if not cl:
			cl = Client(
				first_name = form.first_name.data,
				last_name = form.last_name.data,
				email = form.email.data,
				phone = form.phone.data)
			db.session.add(cl)
		rq = RequestBooking(
			dtStart = form.dateStart.data,
			dtEnd = form.dateEnd.data,
			status = 'new',
			dtStatus = datetime.utcnow(),
			requestor = cl)
		rq.allocate_receipt()
		db.session.add(rq)
		db.session.commit()
		# flash('Thank you, your booking request has been sent', 'success')
		return redirect(url_for('booking_app.track', booking_ref=rq.receipt))
	return render_template('booking/form.html',form=form)

@booking_app.route('/track/<booking_ref>')
def track(booking_ref):
	b = RequestBooking.query.filter_by(receipt=booking_ref).first_or_404()
	if b:
		cl = b.requestor
		return render_template('booking/confirmation.html', booking=b, client=cl)
	else:
		return "<h1>That booking doesn't exist</h1>"

@booking_app.route('/admin/')
@login_required
@roles_required('admin','-bookings')
def admin():
	new_bookings = RequestBooking.query.filter_by(status='new').all()
	confirmed_bookings = RequestBooking.query.filter_by(status='confirmed').all()
	return render_template('booking/admin.html', new_bookings=new_bookings, confirmed_bookings=confirmed_bookings)

@booking_app.route('/approve/<booking_id>')
@login_required
@roles_required('admin','-bookings')
def approve(booking_id):
	booking = RequestBooking.query.get(booking_id)
	if booking:
		booking.status = "confirmed"
		db.session.commit()
		msg = 'Booking %s confirmed' % (booking.receipt)
		flash(msg, 'success')
		return redirect(url_for('booking_app.admin'))

@booking_app.route('/cancel/<booking_id>')
@login_required
@roles_required('admin','-bookings')
def cancel(booking_id):
	booking = RequestBooking.query.get(booking_id)
	if booking:
		booking.status = "cancelled"
		db.session.commit()
		msg = 'Booking %s cancelled' % (booking.receipt)
		flash(msg, 'danger')
		return redirect(url_for('booking_app.admin'))

@booking_app.route('/admin/client/<client_id>')
@login_required
@roles_required('admin','-bookings')
def admin_client(client_id):
	client = Client.query.get(client_id)
	if client:
		bookings = client.find_bookings()
		return render_template('booking/client.html', client=client, bookings=bookings)
	else:
		return redirect(url_for('admin'))

@booking_app.route('/admin/booking/<booking_id>')
@login_required
@roles_required('admin','-bookings')
def admin_booking(booking_id):
	booking = RequestBooking.query.get(booking_id)
	if booking:
		return render_template('booking/booking-detail.html', booking=booking)
	else:
		return redirect(url_for('admin'))

app/templates/_formhelpers.html
{% macro render_field(field) %}
<div class="form-group">
  {{ field.label }}
  {{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class="text-danger">
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
</div>
{% endmacro %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta name="description" content="">
		<meta name="author" content="">
		<link rel="icon" href="../../favicon.ico">

		{% if title %}
			<title>{{ title }} - Gumley Village Hall</title>
		{% else %}
			<title>{% block title %}{% endblock %}Gumley Village Hall</title>
		{% endif %}

		<link href="/static/css/bootstrap.min.css" rel="stylesheet">
		<link href="/static/css/carousel.css" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Cormorant+SC|Noto+Serif" rel="stylesheet">
		<link rel="stylesheet" type="text/css" media="all" href="/static/css/daterangepicker.css" />

		<link href="/static/css/custom.css" rel="stylesheet">

		<style>
			.brandtext {
				font-family: 'Noto Serif', serif;
			}
			.brandtext-lg {
				font-family: 'Cormorant SC', serif;
				font-size: 200%;
			}
			.brandtext-inverse {
				color: black;
			}
			.brandtext-grey {
				color: #9d9d9d;
			}
			.glyph-lg {
				font-size: 300%;
			}
			.footer {
				border-top-width: 3px;
				border-color: #000000;
				background-color: #9d9d9d;
				padding: 30px;
			}
			.contentalign {
				margin-top: 120px;
				max-width: 80%;
			}
			.eventimgmaxh {
				max-height: 200px;
			}
			.navbar-header a {
   				color: #fff;
   				font-weight: bold;
			}
			.hidden {
				.height: 0px;
			}
			.align-right {
				text-align: right;
			}
		</style>

		{% block head %}

		{% endblock %}

	</head>

	 <!-- NAVBAR ================================================== -->
	<body>
		<div class="navbar-wrapper">
			<div class="container">

				<nav class="navbar navbar-inverse navbar-static-top">
					<div class="container">
						<div class="navbar-header">
							<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
							<a class="navbar-brand brandtext-lg" href="{{ url_for('index') }}">Gumley Village Hall</a>
						</div>
						<div id="navbar" class="navbar-collapse collapse">
							<ul class="nav navbar-nav">
								<li><a href="{{ url_for('index') }}">Home</a></li>
				                <li><a href="{{ url_for('gallery') }}">Gallery</a></li>
				                <li><a href="{{ url_for('events') }}">Events</a></li>
				                <li><a href="{{ url_for('contact') }}">Contact Us</a></li>
							</ul>
							<ul class="nav navbar-nav navbar-right">
								<li class="dropdown">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
									<ul class="dropdown-menu">
										{% if g.user.is_authenticated %}
											<li class="dropdown-header">{{ g.user.email }}</li>
											<li><a href="/change">Change Password</a></li>
											<li><a href="https://mail.zoho.eu/zm/" target="_blank">Go to Mail <span class="glyphicon glyphicon-new-window"></span></a>
											<li role="separator" class="divider"></li>
											{% if g.user.has_role('-events') %}
												<li class="dropdown-header">Events Admin</li>
												<li><a href="{{ url_for('event_drafts') }}">View Drafts</a></li>
												<li><a href="{{ url_for('create_event') }}">Create</a></li>
												{% block extra_header %}{% endblock %}
												<li role="separator" class="divider"></li>
											{% endif %}
											{% if g.user.has_role('-bookings') %}
												<li class="dropdown-header">Bookings Admin</li>
												<li><a href="{{ url_for('booking_app.admin') }}">Booking Admin</a></li>
												<li role="separator" class="divider"></li>
											{% endif %}
											{% if g.user.has_role('-database') %}
												<li class="dropdown-header">Database Admin</li>
												<li><a href="/admin/" target="_blank">Access Database Admin</a></li>
												<li role="separator" class="divider"></li>
											{% endif %}
											<li><a href="/logout">Logout</a></li>
										{% else %}
											<li><a href="/login">Login</a></li>
										{% endif %}
									</ul>
								</li>
							</ul>
						</div>
					</div>
				</nav>
			</div>
		</div>

			{% block content %}

			{% endblock %}

		<!-- FOOTER -->
		<footer>
			<div class="container">
				<hr class="footer-hr">
				<p class="pull-right brandtext"><a href="#" class="brandtext-grey">Back to top</a></p>
				<p class="brandtext brandtext-inverse">&copy; 2017 Paul McLear 

				<!-- <a href="#" class="brandtext-grey">Privacy</a> &middot; <a href="#" class="brandtext-grey">Terms</a> -->

				</p>
			</div>
		</footer>

		<!-- Bootstrap core JavaScript
		================================================== -->
		<!-- Placed at the end of the document so the pages load faster -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
		<script src="/static/js/bootstrap.min.js"></script>

		<!-- Just to make our placeholder images work. Don't actually copy the next line! -->
<!-- 		<script src="../../assets/js/vendor/holder.min.js"></script>
 -->		<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<!-- 		<script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
 -->
		{% block extra_scripts %}
		{% endblock %}
	</body>
</html>

app/templates/contact.html
{% extends "base.html" %}

{% block title %}Contact Us - {% endblock %}

{% block content %}

<div class="container contentalign brandtext brandtext-inverse">

	<h2>{% block content_title %}Contact Us{% endblock %}</h2><hr>

	<p>Hold your next event at Gumley Village Hall</p>

	<p>
		Gumley Village Hall sits at the centre of Gumley village and provides a versatile space which can be used for meetings, parties, events, classes.   With beautiful views across south Leicestershire from the rear of the hall, and nestled at the heart of our small village community, it's a friendly and welcoming space for hire.
	</p>
	<p>
		We've had BBQs in the space outside with hungry folk inside and out, children's parties, anniversary dinners and pop up pub nights, quiz nights, WI and ramblers meets, Pilates and yoga, charity events and pop up cafes.  
	</p>
	<p>
		The hall can hired for 2+ hours and provides some parking directly outside or along the quiet village itself.    
	</p>

	<div class="well">

		<p>
			<b>Enquiries:</b><br>
			[Name] <br>
			[Telephone]
		</p>

	</div>

</div>

{% endblock %}

{% block extra_scripts %}


{% endblock %}

app/templates/contact_email.html
<h1>'Contact Us' Message Received</h1>
<h3>The following message has been received from the Web Contact Form:</h3>
<table class="table">
    <tr valign="top">
        <td>Name</td>
        <td>{{ name }}</td>
    </tr><tr>
        <td>Email</td>
        <td>{{ email }}</td>
    </tr><tr>
        <td>Phone</td>
        <td>{{ phone }}</td>
    </tr><tr>
        <td>Message</td>
        <td>{{ message }}</td>
    </tr>
</table>

app/templates/contact_form.html
{% extends "base.html" %}

{% block title %}Contact Us - {% endblock %}

{% block content %}

<div class="container contentalign brandtext brandtext-inverse">

  {% for category, message in get_flashed_messages(with_categories=true) %}
    <div class="alert alert-{{ category }} alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <p>{{ message }}</p>
    </div>
  {% endfor %}

  <h2>{% block content_title %}Contact Us{% endblock %}</h2><hr>

  <div>
    
    <p><strong>Hold your next event at Gumley Village Hall!</strong></p>

    <p>
      Gumley Village Hall sits at the centre of Gumley village and provides a versatile space which can be used for meetings, parties, events, classes.   With beautiful views across south Leicestershire from the rear of the hall, and nestled at the heart of our small village community, it's a friendly and welcoming space for hire.
    </p>
    <p>
      We've had BBQs in the space outside with hungry folk inside and out, children's parties, anniversary dinners and pop up pub nights, quiz nights, WI and ramblers meets, Pilates and yoga, charity events and pop up cafes.  
    </p>
    <p>
      The hall can hired for 2+ hours and provides some parking directly outside or along the quiet village itself.    
    </p>

  </div>

  <br />

  <div class="row">

    <form action="{% block form_action %}{{ url_for('contact') }}{% endblock %}" class="form-horizontal .col-md-8" method="post">

      <div class="form-group">
        <label for="name" class="col-sm-2 control-label">Name</label>
        <div class="col-sm-9">
          <input class="form-control" id="name" name="name" type="text">
        </div>
      </div>

      <div class="form-group">
        <label for="email" class="col-sm-2 control-label">Email</label>
        <div class="col-sm-9">
          <input class="form-control" id="email" name="email" type="text">
        </div>
      </div>

      <div class="form-group">
        <label for="phone" class="col-sm-2 control-label">Phone Number</label>
        <div class="col-sm-9">
          <input class="form-control" id="phone" name="phone" type="text">
        </div>
      </div>

      <div class="form-group">
        <label for="message" class="col-sm-2 control-label">Message</label>
        <div class="col-sm-9">
          <textarea class="form-control" id="message" name="message" style="height: 300px;"></textarea>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-9">
          <p><i>All fields mandatory</i></p>
          <button class="btn btn-primary" type="submit">{% block save_button %}Send{% endblock %}</button>
          <a class="btn btn-default" href="{{ url_for('index') }}">Cancel</a>
        </div>
      </div>

    </form>

  </div>

</div>

{% endblock %}

app/templates/contact_receipt_email.html
<h1>Thank you for your message!</h1>
<p>We'll be in touch shortly.</p>
<p>Regards,</p>
<p>Gumley Village Hall</p>

app/templates/create.html
{% extends "base.html" %}

{% block title %}Create Event - {% endblock %}

{% block content %}

<div class="container contentalign">

  {% for category, message in get_flashed_messages(with_categories=true) %}
    <div class="alert alert-{{ category }} alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <p>{{ message }}</p>
    </div>
  {% endfor %}

  <!-- <h2>Create / Edit Event</h2> -->
  <h2>{% block content_title %}Create Event{% endblock %}</h2>

  <div class="row">

  <form action="{% block form_action %}{{ url_for('create_event') }}{% endblock %}" class="form-horizontal .col-md-8" method="post">

    <div class="form-group">
      <label for="title" class="col-sm-2 control-label">Title</label>
      <div class="col-sm-10">
        <input class="form-control" id="title" name="title" type="text" value="{% if event.title %}{{ event.title }}{% endif %}" placeholder="Enter event title here">
      </div>
    </div>

    <div class="form-group">
      <label for="excerpt" class="col-sm-2 control-label">Excerpt</label>
      <div class="col-sm-10">
        <input class="form-control" id="excerpt" name="excerpt" type="text" value="{% if event.excerpt %}{{ event.excerpt }}{% endif %}" placeholder="Event excerpt will appear on the events page; if not entered, excerpt will be automatically derived from event detail">
      </div>
    </div>

    <div class="form-group">
      <label for="thumbnail" class="col-sm-2 control-label">Thumbnail Image Name</label>
      <div class="col-sm-10">
        <input class="form-control" id="thumbnail" name="thumbnail" type="text" value="{% if event.thumbnail %}{{ event.thumbnail }}{% endif %}">
      </div>
    </div>

    <div class="form-group">
      <label for="event-date" class="col-sm-2 control-label">Event Date</label>
      <div class="col-sm-10">
        <input class="form-control" id="event-date" name="event-date" type="text" {% if event.date %} value="{{ event.date.strftime('%d/%m/%y %H:%M') }}" {% else %} value="" {% endif %}>
        <span><i>Please specify as "dd/mm/yy hh:mm"</i></span>
      </div>
    </div>

    <div class="form-group">
      <label for="Content" class="col-sm-2 control-label">Content</label>
      <div class="col-sm-10">
        <textarea class="form-control" id="content" name="content" style="height: 300px;">{{ event.content }}</textarea>
      </div>
    </div>

    <div class="form-group">
        <label for="published" class="col-sm-2 control-label">Publish</label>
        <div class="col-sm-10 checkbox">
            <input name="published" type="checkbox" value="y"{% if event.published %} checked="checked"{% endif %}><i>(if not checked, event will be saved in drafts)</i>
        </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <button class="btn btn-primary" type="submit">{% block save_button %}Create{% endblock %}</button>
        <a class="btn btn-default" href="{{ url_for('index') }}">Cancel</a>
      </div>
    </div>

  </form>

  </div>

</div>

{% endblock %}

app/templates/detail.html
{% extends "base.html" %}

{% block extra_header %}
  {% if g.user.is_authenticated %}
    <li><a href="{{ url_for('edit_event', slug=event.slug) }}">Edit event</a></li>
  {% endif %}
{% endblock %}

{% block content %}
	<div class="container contentalign brandtext brandtext-inverse">

		{% for category, message in get_flashed_messages(with_categories=true) %}
		<div class="alert alert-{{ category }} alert-dismissable">
		  	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		    <p>{{ message }}</p>
		</div>
		{% endfor %}

		<div class="row">

			<div class="col-md-2">
				<a href="/events" class="btn btn-default"><span class="glyphicon glyphicon-chevron-left"></span> Back to events list</a>
			</div>

			<div class="col-md-6"></div>

			<div class="btn-group pull-right">

				{% if g.user.is_authenticated %}
					<a href="{{ url_for('edit_event', slug=event.slug) }}" style="text-align: right;" class="btn btn-default">
					<span class="glyphicon glyphicon-edit"></span> Edit event</a>
					<a href="{{ url_for('delete_event', slug=event.slug) }}" style="text-align: right;" class="btn btn-default">
					<span class="glyphicon glyphicon-trash"></span> Delete event</a>
				{% endif %}

			</div>

		</div>

		<h2>{{ event.title }}</h2>

		<hr>

		{% if event.date %}
			<div class="well">
				<b>Date:</b> {{ event.date.strftime('%d %B %Y at %H:%M%p') }}
			</div>
		{% endif %}

		{{ event.html_content }}

	</div>
{% endblock %}

app/templates/edit.html
{% extends "create.html" %}

{% block title %}Edit Event - {% endblock %}

{% block content_title %}Edit Event{% endblock %}

{% block form_action %}{{ url_for('edit_event', slug=event.slug) }}{% endblock %}

{% block save_button %}Save changes{% endblock %}

app/templates/events.html
{% extends "base.html" %}

{% block title %}Events - {% endblock %}

{% block content %}

<div class="container contentalign brandtext brandtext-inverse">

	{% for category, message in get_flashed_messages(with_categories=true) %}
	<div class="alert alert-{{ category }} alert-dismissable">
	  	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	    <p>{{ message }}</p>
	</div>
	{% endfor %}

	<h2 id="page-header">{% block content_title %}Events{% endblock %}</h2><hr>

	<div class="row">

		<div class="col-md-2 brandtext brandtext-inverse">

			<br>

			<b>Filter by month:</b>

			<br><br>

			<div id="filters">

				{% for m in months %}

					<a data-filterdate="{{ m[1] }}" class="btn btn-default btn-block month-filter">{{ m[0] }}</a>

				{% endfor %}

			</div>

			<br><a id="clear-filter" class="btn btn-default btn-primary btn-block">Clear Filter</a>

	  	</div>

	  	<div class="col-md-1">

	  	</div>

	  	<div class="col-md-9">

			{% if not events %}
			  <div class="brandtext brandtext-inverse well">
				<i>No events found!</i>
			  </div>
			{% endif %}

			{% for e in events %}
			<div class="event row brandtext brandtext-inverse well" data-eventdate="{{ e.date.strftime('%m%y') }}">
				<div class="col-md-7">
					<a href="{{ url_for('event_detail', slug=e.slug) }}">
						<h2>{{ e.title }}</h2>
					</a>

					{% if e.date %}
						<span class="text-muted">On {{ e.date.strftime('%d %B %Y at %H:%M%p') }}</span>
					{% endif %}
					
					<p>
						{% if e.excerpt %}
							{{ e.excerpt }}
						{% else %}
							{{ e.content|truncate(length=255, killwords=False)|striptags }}
						{% endif %}
					</p>
				</div>
				<div class="col-md-5 thumbnail">
					<img class="featurette-image img-responsive center-block" src="{{ '/static/img/' + e.thumbnail }}" alt="Generic placeholder image">
				</div>

			  </div>

			{% endfor %}

	  	</div>

	</div>

</div>

{% endblock %}

{% block extra_scripts %}

	<script>
		$(document).ready(function() {
			$('#filters').on('click', 'a', function() {
				var did = $(this).data("filterdate");
				var dtext = $(this).text();
				$('.event').not("[data-eventdate=" + did + "]").slideUp();
				$('.event').filter("[data-eventdate=" + did + "]").slideDown();
				$('.month-filter').removeClass('btn-primary');
				$(this).addClass('btn-primary');
				$('#page-header').text('Events - ' + dtext);
			});
			$('#clear-filter').on('click', function() {
				$('.event').slideDown();
				$('.month-filter').removeClass('btn-primary').addClass('btn-default');
				$('#page-header').text('Events');
			});
		});
	</script>

{% endblock %}

app/templates/gallery.html
{% extends "base.html" %}

{% block head %}

<style type="text/css">
	
	body .modal-dialog { /* Width */
	    max-width: 100%;
	    width: auto !important;
	    display: inline-block;
	}
	.modal.in{
	    text-align: center;
	}
	.modal-dialog img {
		max-width: 1200px;
	}

</style>

{% endblock %}

{% block content %}

	<div class="container contentalign brandtext brandtext-inverse">

		<h2>{% block content_title %}Gallery{% endblock %}</h2><hr>

		<div class="row">

		{% for i in images %}

			<div class="col-sm-6 col-md-4">
				<div class="thumbnail">
					<a data-toggle="modal" data-target="#exampleModal" data-spath="{{ '/static/img/gallery/' + i.path }}">
						<img src="{{ '/static/img/gallery/' + i.path }}" style="max-height: 200px;">
					</a>
					{% if i.caption %}
					<div class="caption">
						<p>{{ i.caption|truncate(100,True) }}</p>
					</div>	
					{% endif %}
				</div>
			</div>

		{% endfor %}

		</div>

	</div>

	<div class="modal fade bs-example-modal-lg" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  		<div class="modal-dialog modal-lg" role="document">
			<div class="modal-content">
		  		<div class="modal-body">
		  			<img src=''>
		  		</div>
			  	<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			  	</div>
			</div>
  		</div>
	</div>

{% endblock %}

{% block extra_scripts %}

	<script type="text/javascript">
		
		$('#exampleModal').on('show.bs.modal', function (event) {
			var button = $(event.relatedTarget) // Button that triggered the modal
			var spath = button.data('spath') // Extract info from data-* attributes
			// If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
			// Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
			var modal = $(this)
			modal.find('.modal-body img').attr('src',spath)
		})

	</script>

{% endblock %}

app/templates/home.html
{% extends "base.html" %}

{% block content %}

<!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner brandtext" role="listbox">
        <div class="item active">
          <img class="first-slide" src="/static/img/gumley1.jpg" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h2 class="brandtext">Book the village hall for your next event</h2>
              <p></p>
              <p>
              {% if BOOKING_FORM_ENABLED %}
                <a class="btn btn-lg btn-primary" href="{{ url_for('booking_app.home') }}" role="button">Read more</a></p>
              {% else %}
                <a class="btn btn-lg btn-primary" href="{{ url_for('contact') }}" role="button">Contact Us</a></p>
              {% endif %}
            </div>
          </div>
        </div>
        <div class="item">
          <img class="second-slide" src="/static/img/gumley5.jpg" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h2 class="brandtext">Read about upcoming events at the hall</h2>
              <p></p>
              <p><a class="btn btn-lg btn-primary" href="{{ url_for('events') }}" role="button">View events</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="third-slide" src="/static/img/gumley8-min2.jpg" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h2 class="brandtext">See what's been happening at the hall recently</h2>
              <p></p>
              <p><a class="btn btn-lg btn-primary" href="{{ url_for('gallery') }}" role="button">Browse gallery</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->


	<!-- Marketing messaging and featurettes
	================================================== -->
	<!-- Wrap the rest of the page in another container to center all the content. -->

	<div class="container marketing brandtext">

	  <!-- Three columns of text below the carousel -->
	  <div class="row">
		<div class="col-lg-4">
		  <span class="glyphicon glyphicon-calendar glyph-lg"></span>
		  <h2>Events</h2>
		  <p>View the calendar of upcoming events at Gumley Village Hall</p>
		  <p><a class="btn btn-default" href="{{ url_for('events') }}" role="button">View events &raquo;</a></p>
		</div><!-- /.col-lg-4 -->
		<div class="col-lg-4">
      <span class="glyphicon glyphicon-pencil glyph-lg"></span>
		  <br>
		  <h2>Book the Hall</h2>
		  <p>View rates and book the village hall for your special event</p>
		  <p>
        {% if BOOKING_FORM_ENABLED %}
          <a class="btn btn-default" href="{{ url_for('booking_app.home') }}" role="button">Booking Enquiry &raquo;</a></p>
        {% else %}
          <a class="btn btn-default" href="{{ url_for('contact') }}" role="button">Contact Us &raquo;</a></p>
        {% endif %}
      </p>
		</div><!-- /.col-lg-4 -->
		<div class="col-lg-4">
      <span class="glyphicon glyphicon-camera glyph-lg"></span>
		  <br>
		  <h2>Gallery</h2>
		  <p>Read about what's being going on at the village hall recently</p>
		  <p><a class="btn btn-default" href="{{ url_for('gallery') }}" role="button">Browse gallery &raquo;</a></p>
		</div><!-- /.col-lg-4 -->
	  </div><!-- /.row -->

{% endblock %}